### ISSUE TITLE
Adding Non-equilibrium Green's Function module into postprocessing of DeePTB

### ISSUE THREAD

**Issue by floatingCatty** [deepmodeling/DeePTB#31]
### Describe Current Status and Possible Solution

An important application of the Tight-Binding Model is to simulate transport phenomena with Non-equilibrium Green's Function NEGF methods. This module was determined to enable DeePTB to model electronic devices with multiple electrodes and simulate transport properties accurately. Basic sub-modules are:

1. The NEGF sub-module, which performs the NEGF calculations;
2. The Lead and Device structure modules, which support modelling Devices with scattering regions that are concatenated with several electrodes. Both periodic systems and confined systems are supported.
3. The interfaces between the NEGF module and the Postprocessing module of DeePTB.

**Comment by QG-phy** [comment]
@floatingCatty 在 PR 里面引用issue 就可以。不需要再issue里面引用 PR.
